{"uuid": "187a13dc-d6a9-47aa-b87d-0d9e17b0e8f8", "children": ["543fdf3d-c423-4924-8368-ad904e4d86b6"], "befores": [{"name": "setup", "status": "passed", "start": 1621711215674, "stop": 1621711218020}], "afters": [{"name": "setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=89.0.4389.82)\n\n", "trace": "  File \"/home/tester/.local/lib/python3.8/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/tester/.local/lib/python3.8/site-packages/_pytest/fixtures.py\", line 941, in _teardown_yield_fixture\n    next(it)\n  File \"/home/tester/x_kom_pytest/tests/conftest.py\", line 13, in setup\n    allure.attach(driver.get_screenshot_as_png(), name='Test failed', attachment_type=allure.attachment_type.PNG)\n  File \"/home/tester/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 1064, in get_screenshot_as_png\n    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))\n  File \"/home/tester/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 1074, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)['value']\n  File \"/home/tester/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/home/tester/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1621711218989, "stop": 1621711218991}], "start": 1621711215674, "stop": 1621711218991}